books/urls.py
from django.urls import path
from django.views.generic import TemplateView
from books.views import (
    AboutView,
    AuthorUpdateView,
    AuthorDeleteView,
    MyFormView,
    BookAddView,
    BookUpdateView,
    BookDeleteView,
    PublisherAddView,
    PublisherUpdateView,
    PublisherDeleteView,
)

# from . import views
from books import views

app_name = "books"
urlpatterns = [
    path("", views.index, name="index"),
    path("author/", MyFormView.as_view(), name="new-form"),
    path(
        "author/update/<int:pk>", AuthorUpdateView.as_view(), name="update-author-form"
    ),
    path(
        "author/delete/<int:pk>", AuthorDeleteView.as_view(), name="delete-author-form"
    ),
    path("add-book/", BookAddView.as_view(), name="add-book-form"),
    path("add-book/update/<int:pk>", BookUpdateView.as_view(), name="update-book-form"),
    path("add-book/delete/<int:pk>", BookDeleteView.as_view(), name="delete-book-form"),
    path("add-publisher/", PublisherAddView.as_view(), name="add-publisher-form"),
    path(
        "add-publisher/update/<int:pk>",
        PublisherUpdateView.as_view(),
        name="update-publisher-form",
    ),
    path(
        "add-publisher/delete/<int:pk>",
        PublisherDeleteView.as_view(),
        name="add-publisher-form",
    ),
    path("contact/", views.contact, name="new-contact"),
    path(
        "classification/",
        views.classify_books,
        name="classification-details",
    ),
    path(
        "classification/display/",
        views.display_classify_books,
        name="classification-display",
    ),
    path("details/<int:pk>", views.detail, name="book-details"),
    path("details/author/<int:author_id>", views.author_details, name="author-details"),
    path("search/", views.search),
    path("search/author", views.search_author, name="search-author"),
    path("search/publisher", views.search_publisher, name="search-publisher"),
    path("about/", AboutView.as_view()),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.user_register, name="register"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from mysite import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', views.hello),
    path('time/', views.current_datetime),
    path('time/plus/<int:offset>', views.hours_ahead),
    path('math/<num_1>/<num_2>/', views.mathematics),
    path('valid-date/<int:year>/<int:month>/<int:day>/', views.validate_date),
    path('current-time/', views.current_datetime_2),
    path('athletes/', views.print_athlete_list),
    path('students/', views.print_a_dictionary),
    path('books/', include(('books.urls', 'books'), namespace="books")),
]

books/models.py
import datetime

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import User


class Publisher(models.Model):
    name = models.CharField(_("Name"), max_length=30)
    address = models.CharField(_("Address"), max_length=50)
    city = models.CharField(_("City"), max_length=60)
    state_province = models.CharField(_("Province"), max_length=30)
    country = models.CharField(_("Country"), max_length=50)
    website = models.URLField(_("Website"))

    class Meta:
        verbose_name = "Publisher"
        verbose_name_plural = _("Publishers")

    def __str__(self):
        return f"{self.name} {self.city} {self.country}"


class Author(models.Model):
    first_name = models.CharField(_("First Name"), max_length=30)
    last_name = models.CharField(_("Last Name"), max_length=40)
    email = models.EmailField(_("e-mail"))
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="authors", null=True
    )

    class Meta:
        verbose_name = "Author"
        verbose_name_plural = _("Authors")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Book(models.Model):
    title = models.CharField(_("Title"), max_length=100)
    authors = models.ManyToManyField("books.Author", related_name="books")
    publisher = models.ForeignKey(
        "books.Publisher", on_delete=models.CASCADE, related_name="books"
    )
    classification = models.ForeignKey(
        "books.Classification", on_delete=models.CASCADE, related_name="classifications"
    )
    publication_date = models.DateField()

    class Meta:
        verbose_name = "Book"
        verbose_name_plural = _("Books")

    def was_published_recently(self):
        date_today = timezone.now().date()
        return (
            date_today - datetime.timedelta(days=1)
            <= self.publication_date
            <= date_today
        )

    def __str__(self):
        return f"{self.title}"


class Classification(models.Model):
    code = models.CharField(_("Code"), max_length=3)
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Classification"
        verbose_name_plural = _("Classifications")

    def __str__(self):
        return f"{self.code}"

books/forms.py
from django import forms

from books.models import Author, Book, Publisher, Classification
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

    def clean_sender(self):
        sender = self.cleaned_data.get("sender")

        if sender.split("@")[1] != "mugna.tech":
            raise forms.ValidationError(
                "Sender should only be from a Mugna Organization."
            )

        return sender


class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50)


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = [
            "username",
            "email",
        ]


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = "__all__"
        exclude = ["user"]


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"


class PublisherForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = "__all__"


class AuthorUpdateForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ["first_name", "last_name", "email"]


class BookUpdateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ["title", "authors", "publisher", "classification"]


class PublisherUpdateForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = [
            "name",
            "address",
            "city",
            "state_province",
            "country",
            "website",
        ]


class AuthorDeleteForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = "__all__"
        exclude = ["user"]


class BookDeleteForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ["title", "authors", "publisher", "classification"]


class PublisherDeleteForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = [
            "name",
            "city",
            "country",
            "website",
        ]

books/views.py
from xml.dom import ValidationErr
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.views.generic import TemplateView, View
from books.decorators import allowed_user

from books.models import Book, Author, Classification, Publisher
from books.forms import (
    AuthorForm,
    ContactForm,
    BookForm,
    PublisherForm,
    AuthorUpdateForm,
    BookUpdateForm,
    PublisherUpdateForm,
    AuthorDeleteForm,
    BookDeleteForm,
    PublisherDeleteForm,
    LoginForm,
    RegisterForm,
)


class AboutView(TemplateView):
    template_name = "books/about.html"


""" ADDING OF AUTHORS, BOOKS, PUBLISHERS """


@method_decorator(login_required(login_url="books:login"), name="dispatch")
@method_decorator(allowed_user(allowed_roles=["Admin"]), name="dispatch")
class MyFormView(View):
    form_class = AuthorForm
    initial = {"key": "value"}
    template_name = "books/author.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)

        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            # Clean data here
            form.save()
            messages.success(request, "Successfully Added Author")
            return HttpResponseRedirect(reverse("books:new-form"))

        return render(request, self.template_name, {"form": form})


@method_decorator(login_required(login_url="books:login"), name="dispatch")
@method_decorator(allowed_user(allowed_roles=["Admin"]), name="dispatch")
class BookAddView(View):
    form_class = BookForm
    initial = {"key": "value"}
    template_name = "books/book_add.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # Clean data here
            form.save()
            messages.success(request, "Successfully Added Book")
            return HttpResponseRedirect(reverse("books:add-book-form"))

        return render(request, self.template_name, {"form": form})


@method_decorator(login_required(login_url="books:login"), name="dispatch")
@method_decorator(allowed_user(allowed_roles=["Admin"]), name="dispatch")
class PublisherAddView(View):
    form_class = PublisherForm
    initial = {"key": "value"}
    template_name = "books/publisher_add.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # Clean data here
            form.save()
            messages.success(request, "Successfully Added Publisher")
            return HttpResponseRedirect(reverse("books:add-publisher-form"))

        return render(request, self.template_name, {"form": form})


""" 
UPDATING OF AUTHORS, BOOKS, PUBLISHERS 
To populate fields use instance= as 2nd argument when initializing a form
get the .id of whichever model instance used
"""


@method_decorator(login_required(login_url="books:login"), name="dispatch")
@method_decorator(allowed_user(allowed_roles=["Admin"]), name="dispatch")
class AuthorUpdateView(View):
    form_class = AuthorUpdateForm
    initial = {"key": "value"}
    template_name = "books/author_update.html"

    def get(self, request, pk, *args, **kwargs):
        author_update = Author.objects.get(pk=pk)
        form = self.form_class(initial=self.initial, instance=author_update)
        return render(request, self.template_name, {"form": form})

    def post(self, request, pk, *args, **kwargs):
        author_update = Author.objects.get(pk=pk)
        form = self.form_class(request.POST, instance=author_update)
        if form.is_valid():
            # Clean data here
            form.save()
            messages.success(request, "Successfully Updated Author")
            return redirect("books:update-author-form", author_update.id)

        return render(request, self.template_name, {"form": form})


@method_decorator(login_required(login_url="books:login"), name="dispatch")
@method_decorator(allowed_user(allowed_roles=["Admin"]), name="dispatch")
class BookUpdateView(View):
    form_class = BookUpdateForm
    initial = {"key": "value"}
    template_name = "books/book_update.html"

    def get(self, request, pk, *args, **kwargs):
        book_update = Book.objects.get(pk=pk)
        form = self.form_class(initial=self.initial, instance=book_update)
        return render(request, self.template_name, {"form": form})

    def post(self, request, pk, *args, **kwargs):
        book_update = Book.objects.get(pk=pk)
        form = self.form_class(request.POST, instance=book_update)
        if form.is_valid():
            # Clean data here
            form.save()
            messages.success(request, "Successfully Updated Book")
            return redirect("books:update-book-form", book_update.id)

        return render(request, self.template_name, {"form": form})


@method_decorator(login_required(login_url="books:login"), name="dispatch")
@method_decorator(allowed_user(allowed_roles=["Admin"]), name="dispatch")
class PublisherUpdateView(View):
    form_class = PublisherUpdateForm
    initial = {"key": "value"}
    template_name = "books/publisher_update.html"

    def get(self, request, pk, *args, **kwargs):
        publisher_update = Publisher.objects.get(pk=pk)
        form = self.form_class(initial=self.initial, instance=publisher_update)
        return render(request, self.template_name, {"form": form})

    def post(self, request, pk, *args, **kwargs):
        publisher_update = Publisher.objects.get(pk=pk)
        form = self.form_class(request.POST, instance=publisher_update)
        if form.is_valid():
            # Clean data here
            form.save()
            messages.success(request, "Successfully Updated Publisher")
            return redirect("books:update-publisher-form", publisher_update.id)

        return render(request, self.template_name, {"form": form})


""" 
DELETION OF AUTHORS, BOOKS, PUBLISHERS 
To populate fields use instance= as 2nd argument when initializing a form
get the .id of whichever model instance used
"""


@method_decorator(login_required(login_url="books:login"), name="dispatch")
@method_decorator(allowed_user(allowed_roles=["Admin"]), name="dispatch")
class AuthorDeleteView(View):
    form_class = AuthorDeleteForm
    initial = {"key": "value"}
    template_name = "books/author_delete.html"

    def get(self, request, pk, *args, **kwargs):
        author_delete = Author.objects.get(pk=pk)
        form = self.form_class(initial=self.initial, instance=author_delete)
        return render(request, self.template_name, {"form": form})

    def post(self, request, pk, *args, **kwargs):
        author_delete = Author.objects.get(pk=pk)
        form = self.form_class(request.POST, instance=author_delete)
        if form.is_valid():
            # Clean data here
            author_delete.delete()
            messages.success(request, "Successfully Deleted Author")
            return redirect("books:new-form")

        return render(request, self.template_name, {"form": form})


@method_decorator(login_required(login_url="books:login"), name="dispatch")
@method_decorator(allowed_user(allowed_roles=["Admin"]), name="dispatch")
class BookDeleteView(View):
    form_class = BookDeleteForm
    initial = {"key": "value"}
    template_name = "books/book_delete.html"

    def get(self, request, pk, *args, **kwargs):
        book_delete = Book.objects.get(pk=pk)
        form = self.form_class(initial=self.initial, instance=book_delete)
        return render(request, self.template_name, {"form": form})

    def post(self, request, pk, *args, **kwargs):
        book_delete = Book.objects.get(pk=pk)
        form = self.form_class(request.POST, instance=book_delete)
        if form.is_valid():
            # Clean data here
            book_delete.delete()
            messages.success(request, "Successfully Deleted Book")
            return redirect("books:add-book-form")

        return render(request, self.template_name, {"form": form})


@method_decorator(login_required(login_url="books:login"), name="dispatch")
@method_decorator(allowed_user(allowed_roles=["Admin"]), name="dispatch")
class PublisherDeleteView(View):
    form_class = PublisherDeleteForm
    initial = {"key": "value"}
    template_name = "books/publisher_delete.html"

    def get(self, request, pk, *args, **kwargs):
        pub_delete = Publisher.objects.get(pk=pk)
        form = self.form_class(initial=self.initial, instance=pub_delete)
        return render(request, self.template_name, {"form": form})

    def post(self, request, pk, *args, **kwargs):
        pub_delete = Publisher.objects.get(pk=pk)
        form = self.form_class(request.POST, instance=pub_delete)
        if form.is_valid():
            # Clean data here
            pub_delete.delete()
            messages.success(request, "Successfully Deleted Publisher")
            return redirect("books:add-publisher-form")

        return render(request, self.template_name, {"form": form})


@login_required(login_url="books:login")
@allowed_user(allowed_roles=["Admin", "User"])
def index(request):
    book_list = Book.objects.all()
    # output = [book for book in book_list]
    response = ""

    if not book_list:

templates/books/author.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Authors</title>
</head>
<body>
  <form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
  </form>
</body>
</html>

templates/books/author_delete.html
{% extends 'books/base_exer_3.html' %}

{% block content %}
    <h1>Delete Author</h1>
    <hr>
    {% include 'books/messages.html' %}
    <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Delete">
    </form>
    
{% endblock %}

templates/books/author_details.html
{% extends 'books/base_exer_3.html' %}

{% block content %}
<h1>Details</h1>
<dl>
  <dt>First Name:</dt>
  <dd>{{ author_detail.first_name }}</dd>
  <dt>Last Name:</dt>
  <dd>{{ author_detail.last_name }}</dd>
  <dt>Email:</dt>
  <dd>{{ author_detail.email }}</dd>
</dl>

<h1>Other Books by {{ author_detail }}</h1>

{% for book in book_detail %}
 <ul>
    <a href="{% url 'books:book-details' book.id %}"><li>{{ book }}</li></a>
 </ul>
{% endfor %}
    
{% endblock %}

templates/books/book_delete.html
{% extends 'books/base_exer_3.html' %}

{% block content %}
    <h1>Delete Book</h1>
    <hr>
    {% include 'books/messages.html' %}
    <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Delete">
    </form>
    
{% endblock %}

templates/books/book_list.html
{% extends 'books/base_exer_3.html' %}

{% block content %}
    <strong>Welcome {{ username }}</strong>
    <p>
        {% for book in book_list %}
        <ul>
            <a href="{% url 'books:book-details' book.id %}"><li>{{ book.title }}</li></a>
        </ul>
        {% endfor%}
    </p>
{% endblock %}

templates/books/classification_display.html
{% extends 'books/base_exer_3.html' %}

{% block content %}
    <h1>Books in</h1>

    {% for classify in classify_books %}
        <ul>
            <li>{{ classify.title }}</li>
        </ul>
    {% endfor %}
{% endblock %}

templates/books/login.html
{% extends 'books/base_exer_3.html' %}

{% block content %}
  <h1>Login Form</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Log In">
      </form>
      <p> Don't have an account yet? <a href="{% url 'books:register' %}">Register Now</a></p>
{% endblock %}

templates/books/messages.html
{% if messages %}
    {% for message in messages %}
        <strong style="color: green;">{{ message }}</strong>
    {% endfor %}
{% endif %}

templates/books/publisher_add.html
{% extends 'books/base_exer_3.html' %}

{% block content %}
  <h1>Add New Publisher</h1>
  <hr>
  {% include 'books/messages.html' %}
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>
    
{% endblock %}

templates/books/search_author_results.html
{% extends 'books/base_exer_3.html' %}

{% block content %}
    {% include "books/search_author.html" %}
    {% if authors %}
    <p>Found {{ authors|length }} author{{ authors|pluralize }}.</p>
    <ul>
        {% for author in authors %}
            <li>{{ author.first_name }} {{ author.last_name }}</li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No authors matched your search criteria.</p>
    {% endif %}
{% endblock %}

templates/books/search_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
</head>
<body>
    <h1>Search for books</h1>
    {% if error %}
        <p style="color: red;" >Please submit a search term</p>
    {% endif %}
    <form action="" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
    
</body>
</html>

templates/books/search_publishers.html
{% extends 'books/base_exer_3.html' %}

{% block content %}
    <h1>Search for a Publisher</h1>
    {% if error %}
        <p style="color: red;" >Please submit a search term</p>
    {% endif %}
    <form action="" method="get">
        <input type="text" name="query">
        <input type="submit" value="Search">
    </form>
{% endblock %}

templates/books/search_publishers_results.html
{% extends 'books/base_exer_3.html' %}

{% block content %}
    {% include "books/search_publishers.html" %}
    {% if publishers %}
    <p>Found {{ publishers|length }} publisher{{ publisher|pluralize }}.</p>
    <ul>
        {% for publisher in publishers %}
            <li>{{ publisher.name }}</li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No authors matched your search criteria.</p>
    {% endif %}
{% endblock %}

templates/books/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
</head>
<body>
    {% include "books/search_form.html" %}
    {% if books %}
        <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
        <ul>
            {% for book in books %}
                <li>{{ book.title }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No books matched your search criteria.</p>
    {% endif %}
</body>
</html>